### ISSUE TITLE
Infografía Unidad 2

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/infografia-de-las-librerias-Lissete7#2]
![Infografia Unidad2_Lizzete León González](https://user-images.githubusercontent.com/79929632/114817812-4a214080-9d80-11eb-991a-b1e609cfe793.png)

**Comment by Sandra631** [comment]
[RUBRICA_PARA_EVALUAR_UNA_INFOGRAFIA .pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-Lissete7/files/6361803/RUBRICA_PARA_EVALUAR_UNA_INFOGRAFIA.pdf)

**Comment by Sandra631** [comment]
20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
